shell = "zsh"

# コマンドの入力履歴に基づくサジェスト
[plugins.zsh-autosuggestions]
git = "https://github.com/zsh-users/zsh-autosuggestions"
use = ["zsh-autosuggestions.zsh"]

# コマンドのシンタックスハイライト（色付け）
[plugins.zsh-syntax-highlighting]
git = "https://github.com/zsh-users/zsh-syntax-highlighting"
use = ["zsh-syntax-highlighting.zsh"]